name = "lumen"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d78a33385b5f4556b362210572dad83f"

[[kv_namespaces]]
binding = "USAGE"
id = "89fa417d14584138807202f3748e041a"

[observability]
enabled = true
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
NEURON_DAILY_LIMIT = "10000"
NEURON_SOFT_LIMIT = "9800"
